---
- name: Ping
  hosts: all
  gather_facts: False
  connection: local

  tasks:

  - name: do random
    ansible.builtin.shell: echo $(($RANDOM % 2))
    args:
      executable: /bin/bash
    register: diff_cmd
    failed_when: diff_cmd.rc == 0
    delegate_to: localhost

  - name:  add devices with connectivity to the "working_hosts" group
    group_by:
      key: working_hosts

  - name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        myinventory:  "{{ groups['working_hosts'] }}"
    run_once: True