---
- name: Ping
  hosts: "{{ myinventory | default('all') }}"
  gather_facts: False
  connection: local

  tasks:

  - name: do random
    shell: echo $(($RANDOM % 2))
    register: diff_cmd
    failed_when: '"1" not in diff_cmd.stdout'
    delegate_to: localhost

  - name:  add devices with connectivity to the "working_hosts" group
    group_by:
      key: working_hosts

  - name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        myinventory:  "{{ groups['working_hosts'] }}"
    run_once: True